### PR TITLE
Create UI of send email

### LINKED ISSUE #7: Make UI for email send page
The user should have the following features
1. Can choose from limited email using dropdown 
2. Can write message in text area, (should be big enough)
3. Can send message
4. Should see an message pop up / notification alert on success

The expected UI
image

### PR DESCRIPTION
**Pull request by Aftabsattar**
Please check this and assign me some more issues

### CODE REVIEW

**Comment by ZU3AIRE** [comment]
Firstly this form was to be added on a new page with route `/send-email` you can check this in the issue its mention in the image.
Secondly, Here is a minor padding issue 
image

**Comment by ZU3AIRE** [comment]
> Firstly this form was to be added on a new page with route `/send-email` you can check this in the issue its mention in the image. Secondly, Here is a minor padding issue image

@Aftabsattar

**Comment by ZU3AIRE** [comment]
@Aftabsattar please do the required changes so we can merge this PR

**Comment by Aftabsattar** [comment]
check this i am fix padding and routing issues

**Comment by ZU3AIRE** [comment]
@Aftabsattar everything works fine in `/send-email`
but everything in `/` and `/inbox` is changed unnecessarily 
Please revert the changes in `/` and `/inbox`

**Comment by Aftabsattar** [comment]
@ZU3AIRE  please review that every thing is fine?

**Review by ZU3AIRE — APPROVED** [review]

**Pull request merged**
